import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Chart from "../components/Chart";
import List from "../components/List";
import styles from "../styles/Home.module.css";
import { v4 as uuidv4 } from "uuid";

export type ToDo = {
	key: string;
	name: string;
	category: Category;
	done: boolean;
};

export type Category = {
	key: string;
	name: string;
};

export const NEW_CATEGORY_KEY = "new";
export const ALL_CATEGORY_KEY = "all";

const Home: NextPage = () => {
	const [categories, setCategories] = useState<Category[]>([]);
	const [toDos, setToDos] = useState<ToDo[]>([]);

	const addToDo = (toDo: ToDo) => {
		setToDos([toDo, ...toDos]);
	};

	const deleteToDo = (key: string) => {
		setToDos(toDos.filter((toDo) => toDo.key !== key));
	};

	const updateToDo = (key: string, newToDo: Partial<ToDo>) => {
		setToDos(
			toDos.map((toDo) => (toDo.key === key ? { ...toDo, ...newToDo } : toDo))
		);
	};

	const addCategory = (): Category => {
		const newName = window.prompt("Enter name for new category");
		const newCategory = { key: uuidv4(), name: newName || "" };
		setCategories([newCategory, ...categories]);
		return newCategory;
	};

	return (
		<>
			<Head>
				<title>To-do app</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1 className={styles.pagetitle}>To-do</h1>
			<main className={styles.container}>
				<List
					categories={categories}
					toDos={toDos}
					onAddToDo={addToDo}
					onDeleteToDo={deleteToDo}
					onUpdateToDo={updateToDo}
					createCategory={addCategory}
				/>
				<Chart categories={categories} toDos={toDos} />
			</main>
		</>
	);
};

export default Home;
