import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import MojaaBarChart from "../components/MojaaBarChart";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mojaa Frontend Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Welcome to the Mojaa Frontend take home exercise!</h1>
        <p className={styles.mojaatextwidth}>
          Create a todo list application, with multiple categories, and a graph
          that displays the status of the todo list categories (how many items
          are there total, how many are done, how many aren&apos;t).
        </p>
        <p className={styles.mojaatextwidth}>
          The application should be able to add, edit, and delete todo items and
          categories. Items should belong to a single category.
        </p>
        <p className={styles.mojaatextwidth}>
          We&apos;ve included{" "}
          <Link href="https://github.com/recharts/recharts">
            <a className={styles.mojaalink}>recharts</a>
          </Link>{" "}
          as a dependency in this project, but you are free to use any charting
          library that you wish.
        </p>{" "}
        <p className={styles.mojaatextwidth}>
          The current state of the styling is deliberately minimal, you should
          use this as an opportunity to demonstrate your design skills. Please{" "}
          add/remove dependencies and styles as you think necessary. Being able
          to explain why you made any design choices from the perspective of the
          user is a bonus.
        </p>{" "}
        <MojaaBarChart />
        <p className={styles.mojaatextwidth}>
          The easiest way to deploy your Next.js app is to use the{" "}
          <Link href="https://vercel.com/new?utm_medium=default-template&filter=next.js&utm_source=create-next-app&utm_campaign=create-next-app-readme)">
            <a className={styles.mojaalink}>Vercel Platform</a>
          </Link>{" "}
          (use a free, no custom domain plan).
        </p>
        <p className={styles.mojaatextwidth}>
          Please email rory@mojaa.tech with a link to your project in a public
          GitHub repository on completion of the task.
        </p>
      </main>
    </div>
  );
};

export default Home;
